In [1]:
import pandas as pd
import numpy as np

In [2]:


df = pd.read_csv("IRIS.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [4]:
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [5]:
#label encoder
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

df['species'] = lb.fit_transform(df['species'])
df

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [6]:
X=df.drop(['species'], axis=1)
y=df['species']

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [8]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)
print(knn.score(X_train, y_train))
print(knn.score(X_test, y_test))

from sklearn.metrics import confusion_matrix
y_pred = knn.predict(X_test)
print(confusion_matrix(y_pred,y_test))

0.9619047619047619
0.9777777777777777
[[16  0  0]
 [ 0 17  0]
 [ 0  1 11]]


In [9]:

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
print(knn.score(X_train, y_train))
print(knn.score(X_test, y_test))

from sklearn.metrics import confusion_matrix
y_pred = knn.predict(X_test)
print(confusion_matrix(y_pred,y_test))

0.9714285714285714
0.9777777777777777
[[16  0  0]
 [ 0 17  0]
 [ 0  1 11]]


In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train,y_train)
print(knn.score(X_train, y_train))
print(knn.score(X_test, y_test))

from sklearn.metrics import confusion_matrix
y_pred = knn.predict(X_test)
print(confusion_matrix(y_pred,y_test))

0.9714285714285714
0.9777777777777777
[[16  0  0]
 [ 0 17  0]
 [ 0  1 11]]
